Rails.application.routes.draw do
	root 'login#login'
	get '/log_user' => 'login#log_user'
	get '/dashboard' => 'dashboard#dashboard'
	get '/profile_information' => 'account#profile_information'
	get '/account_settings' => 'account#account_settings'
	get '/add_building' => 'building_options#add_building'
	get '/account_settings' => 'account#account_settings'
	get '/create_account' => 'account#create_account'
	post '/redirect_account' => 'account#redirect_account'
	get '/view_buildings' => 'view_buildings#view_buildings'
	post '/view_buildings' => 'view_buildings#view_buildings'
	get '/logout' => 'login#logout'
	get '/edit/account_settings' => 'account#edit_account_settings'
	get '/edit/profile_information' => 'account#edit_profile_information'
	get '/update/account_settings' => 'account#update_account_settings'
	get '/update/profile_information' => 'account#update_profile_information'
end
