# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d431b00fd1dc56ac37b9d134333358231dbca0bd6b70ded26c58bc2e9dcdae2348357c949b3a0781561f4bec6dce4b669ecbe46641d67f8bb0d5e7cb3db8b6

test:
  secret_key_base: 273c3e91d7930a0f8ade219993735c34b89dd77dc957b71057f1cb2c1e711c2c6adb76f16d9ebd5f3adf99579ae06e4f20c4a7ff2a1a586efa395e742e29986b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
